import { NextResponse } from "next/server";

const CHECKLIST = `# New Bird Owner Checklist
## The Aviary

### Before You Buy
- [ ] Research your chosen species thoroughly
- [ ] Find an avian veterinarian in your area
- [ ] Calculate monthly costs (food, toys, vet)
- [ ] Ensure no household toxins (Teflon, avocados, etc.)
- [ ] Get household members on board

### Cage & Setup
- [ ] Appropriate cage size (1.5x wingspan minimum width)
- [ ] Correct bar spacing for species
- [ ] Multiple perch diameters (natural wood preferred)
- [ ] Stainless steel food and water dishes
- [ ] Cuttlebone or mineral block
- [ ] Cage liner or paper for easy cleaning
- [ ] Safe location (no drafts, direct sun, or kitchen fumes)

### Food & Supplies
- [ ] Species-appropriate seed mix or pellets
- [ ] Fresh vegetables and fruits guide
- [ ] Grit (for species that require it)
- [ ] Treats for training and bonding

### Enrichment
- [ ] 3-5 safe toys (rotate weekly)
- [ ] Foraging toys or activities
- [ ] Bathing dish or spray bottle
- [ ] Mirror (if appropriate for species)

### First Week
- [ ] Quiet adjustment period (3-7 days)
- [ ] Monitor eating and drinking
- [ ] Schedule avian vet checkup
- [ ] Begin trust-building with treats
- [ ] Establish daily routine

---
Generated by The Aviary — theaviaryguide.com
`;

export async function GET() {
  return new NextResponse(CHECKLIST, {
    headers: {
      "Content-Type": "text/markdown",
      "Content-Disposition": 'attachment; filename="new-bird-owner-checklist.md"',
    },
  });
}
